version: '3'

services:

  crypto_assets_db:
    container_name: crypto_assets_db
    image: mdillon/postgis:11
    restart: unless-stopped

  crypto_assets_api:
    container_name: crypto_assets_api
    build: .
    restart: unless-stopped
    depends_on:
      - crypto_assets_db
    volumes:
      - /var/www/crypto_assets/static:/app/crypto_assets/static
    ports:
      - "127.0.0.1:4381:80"

  crypto_assets_celery:
    container_name: crypto_assets_celery
    build: .
    working_dir: /app/crypto_assets
    command: ["celery", "-A", "crypto_assets", "worker", "-l", "info"]
    restart: unless-stopped
    depends_on:
      - crypto_assets_db
      - crypto_assets_redis

  crypto_assets_beat:
    container_name: crypto_assets_beat
    build: .
    working_dir: /app/crypto_assets
    command: ["celery", "-A", "crypto_assets", "beat", "-l", "info", "--pidfile=/tmp/celeryd.pid"]
    restart: unless-stopped
    depends_on:
      - crypto_assets_db
      - crypto_assets_redis

  crypto_assets_redis:
    container_name : crypto_assets_redis
    image: redis:5.0.14
    restart: unless-stopped
